server:
  port: 8120 # 服务端口

spring:
#  profiles:
#    active: dev # 环境设置
#  application:
#    name: service-oss # 服务名
  #spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址

aliyun:
  oss:
    endpoint: oss-us-west-1.aliyuncs.com
    keyid: LTAI4GFsmNMKyZva6rnWGZs4
    keysecret: vcRRFKDgiLRePOZcQ1qvO3S48ISdhj
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketname: sungwa-school